[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
keys = [
  "/services/web"
]
reload_cmd = "/usr/local/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg && /usr/bin/supervisorctl restart haproxy"